### ISSUE TITLE
Unexpected Token Export Issue In Index.js File

### ISSUE THREAD

**Issue by oarabilekoore** [RodnyE/droidscript-sdk#1]
When running in ds, following error occured: 
/storage/emulated/0/Android/data/com.smartphoneremote.androidscriptfree/files/DroidScript/droidscript sdkTest/node_modules/droidscript-sdk/lib/index.js:4
export * from './utils/utils.js'
^^^^^^

SyntaxError: Unexpected token 'export'
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1055:15)
at Module._compile (node:internal/modules/cjs/loader:1090:27)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
at Module.load (node:internal/modules/cjs/loader:1004:32)
at Function.Module._load (node:internal/modules/cjs/loader:839:12)
at Module.require (node:internal/modules/cjs/loader:1028:19)
at require (node:internal/modules/cjs/helpers:102:18)
at globalThis.require (/data/data/com.smartphoneremote.androidscriptfree/app_node/node.js:13:44)
at /storage/emulated/0/Android/data/com.smartphoneremote.androidscriptfree/files/DroidScript/droidscript sdkTest/droidscript sdkTest.js:13:13'
ERROR: Unexpected token 'export', Line 4, index.js

**Comment by rodnye** [comment]
Hello! Sorry for responding so late, well, very late, haha. This module uses JavaScript ESM so that you can use only the methods you need, thus avoiding polluting the global context of your code. That’s why the problem with the export arises. You should use a bundler like Webpack for the proper transpilation of the project.
